### ISSUE TITLE
broken by sexpdata 0.0.4

### ISSUE THREAD

**Issue by glyph** [tkf/python-epc#11]
See https://github.com/jd-boyd/sexpdata/issues/36

**Comment by pawciobiel** [comment]
```
ERROR:epc:Unexpected error
Traceback (most recent call last):
  File "/home/pgb/.emacs.d/.python-environments/default/lib/python3.10/site-packages/epc/handler.py", line 238, in _handle
    (name, uid, args) = unpack_message(sexp)
  File "/home/pgb/.emacs.d/.python-environments/default/lib/python3.10/site-packages/epc/handler.py", line 87, in unpack_message
    return (data[0].value(), data[1], data[2:])
AttributeError: 'Symbol' object has no attribute 'value'
```

related to https://github.com/tkf/emacs-jedi/issues/348

**Comment by jd-boyd** [comment]
Would you mind trying to test if 1.0.1 fixed this? You need to install it from github since that version isn't released yet.

Alternatively, could you post an example of how to trigger the above error in a few lines of python code without requiring an entire emacs setup?  Is it triggered by running python-epc's unit tests?

**Comment by glyph** [comment]
1.0.1 did fix this for me.
